# Generated by Django 5.0.4 on 2024-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core_post.post'),
        ),
    ]
